branches:
  only:
  - main

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  # Tagging
  - docker tag udagram-api-feed ludten/udagram-api-feed:v3
  - docker tag udagram-api-user ludten/udagram-api-user:v3
  - docker tag udagram-frontend ludten/udagram-frontend:v3
  - docker tag reverseproxy ludten/reverseproxy:v3

# Push
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ludten/udagram-api-feed:v3
  - docker push ludten/udagram-api-user:v3
  - docker push ludten/udagram-frontend:v3
  - docker push ludten/reverseproxy:v3
